# Site settings
title: JeffreyFrancesco.org
email: jeffrey.francesco@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  主に北近畿を中心に、ハモンドオルガン &amp; 鍵盤ハーモニカ奏者・インターネットラジオ
  MC・Web 制作者 etc. として細々と活動を続ける Jeffrey Francesco (JF) の個人サイトです。
  Live 出演情報、音楽活動や Web 制作に関する雑記などをメインに公開しています。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jeffreyfrancesco.org" # the base hostname & protocol for your site
twitter_username: JForg
github_username:  jforg

timezone: "Asia/Tokyo"

# Build settings
source: source
destination: home

permalink: /:categories/:title/
excerpt_separator: "<!-- more -->"

# Markdown converter settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: false
  entity_output: numeric
  enable_coderay: false
