# Site settings
title: JeffreyFrancesco.org
description: > # this means to ignore newlines until "baseurl:"
  主に北近畿を中心に、ハモンドオルガン &amp; 鍵盤ハーモニカ奏者・インターネットラジオ
  MC・Web 制作者 etc. として細々と活動を続ける Jeffrey Francesco (JF) の個人サイトです。
  Live 出演情報、音楽活動や Web 制作に関する雑記などをメインに公開しています。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jeffreyfrancesco.org" # the base hostname & protocol for your site

timezone: "Asia/Tokyo"

# Build settings
source: source
destination: gh-pages
gems:
- jekyll-sitemap
- jekyll-archives
permalink: /:categories/:title/
excerpt_separator: "<!-- more -->"
exclude: [tests]
keep_files: [.git, assets]

# Markdown converter settings
markdown: kramdown
kramdown:
  auto_ids: false
  entity_output: numeric
  hard_wrap: true
  syntax_highlighter: nil

# Archive-pages settings
jekyll-archives:
  enabled: [year, tags, categories]
  layouts:
    year:  'year'
    tag: 'tag'
    category: 'category'
  permalinks:
    year:  '/:year/'
    tag: '/tag/:name/'
    category: '/:name/all/'

# auto_title plugin settings
auto_title:
  separator: '/'
  templates:
    year: 'Archives: #{year}年に公開された記事一覧 #{separator} #{site_title}'
    tag:  'Archives: タグ「#{page_title}」が付けられた記事一覧 #{separator} #{site_title}'
    category:  'Archives: #{category_name} の記事一覧 #{separator} #{site_title}'
auto_description:
  truncate:
    length: 128
    omission: '…'
  templates:
    year: 'JeffreyFrancesco.org のコンテンツのうち、#{year}年に公開された記事のタイトル一覧です。日付の新しいものから順に、月ごとにセクションを分けて表示しています。'
    tag:  'JeffreyFrancesco.org のコンテンツのうち、タグ「#{title}」が付けられた記事のタイトル一覧です。日付の新しいものから順に、年ごとにセクションを分けて表示しています。'
    category: 'JeffreyFrancesco.org のコンテンツのうち、「#{category_name}」に公開された記事のタイトル一覧です。日付の新しいものから順に、年ごとにセクションを分けて表示しています。'
