# Site settings
title: JeffreyFrancesco.org
description: > # this means to ignore newlines until "baseurl:"
  主に北近畿を中心に、ハモンドオルガン &amp; 鍵盤ハーモニカ奏者・インターネットラジオ
  MC・Web 制作者 etc. として細々と活動を続ける Jeffrey Francesco (JF) の個人サイトです。
  Live 出演情報、音楽活動や Web 制作に関する雑記などをメインに公開しています。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jeffreyfrancesco.org" # the base hostname & protocol for your site

timezone: "Asia/Tokyo"

# Build settings
source: source
destination: gh-pages
gems:
- jekyll-sitemap
- jekyll-assets
- jekyll-assets/rails-assets
- jekyll-archives
permalink: /:categories/:title/
excerpt_separator: "<!-- more -->"

# Markdown converter settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: false
  entity_output: numeric
  enable_coderay: false

# Asset pipeline settings
assets:
  css_compressor: sass

# Archive-pages settings
jekyll-archives:
  enabled: [year, tags]
  layouts:
    year:  'year'
    tag: 'tag'
  permalinks:
    year:  '/:year/'
    tag: '/tags/:name/'
    category: '/:name/all/'

# auto_title plugin settings
auto_title:
  separator: '/'
  templates:
    year: 'Archives: #{year}年に公開されたコンテンツ一覧 #{separator} #{site_title}'
    tag:  'Archives: タグ「#{page_title}」が付けられたコンテンツ一覧 #{separator} #{site_title}'
auto_description:
  truncate:
    length: 128
    omission: '…'
  templates:
    year: 'JeffreyFrancesco.org のコンテンツのうち、#{year}年に公開されたもののタイトル一覧です。日付の古いものから順に、月ごとにセクションを分けて表示しています。'
    tag:  'JeffreyFrancesco.org のコンテンツのうち、タグ「#{title}」が付けられたもののタイトル一覧です。日付の新しいものから順に表示しています。'
